# Generated by Django 4.1.7 on 2023-03-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_director_genre_movie_director_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
